/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    blogPosts: BlogPost;
    'payload-kv': PayloadKv;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    blogPosts: BlogPostsSelect<false> | BlogPostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogPosts".
 */
export interface BlogPost {
  id: number;
  slug: string;
  title: string;
  description?: string | null;
  content?:
    | (
        | {
            paragraph?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'Paragraph';
          }
        | {
            code?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'Code';
          }
        | {
            showMultiplePackageOptions?: boolean | null;
            codeLanguage?:
              | (
                  | 'abap'
                  | 'actionscript-3'
                  | 'ada'
                  | 'angular-html'
                  | 'angular-ts'
                  | 'apache'
                  | 'apex'
                  | 'apl'
                  | 'applescript'
                  | 'ara'
                  | 'asciidoc'
                  | 'asm'
                  | 'astro'
                  | 'awk'
                  | 'ballerina'
                  | 'bat'
                  | 'beancount'
                  | 'berry'
                  | 'bibtex'
                  | 'bicep'
                  | 'blade'
                  | 'bsl'
                  | 'c'
                  | 'cadence'
                  | 'cairo'
                  | 'clarity'
                  | 'clojure'
                  | 'cmake'
                  | 'cobol'
                  | 'codeowners'
                  | 'codeql'
                  | 'coffee'
                  | 'common-lisp'
                  | 'coq'
                  | 'cpp'
                  | 'crystal'
                  | 'csharp'
                  | 'css'
                  | 'csv'
                  | 'cue'
                  | 'cypher'
                  | 'd'
                  | 'dart'
                  | 'dax'
                  | 'desktop'
                  | 'diff'
                  | 'docker'
                  | 'dotenv'
                  | 'dream-maker'
                  | 'edge'
                  | 'elixir'
                  | 'elm'
                  | 'emacs-lisp'
                  | 'erb'
                  | 'erlang'
                  | 'fennel'
                  | 'fish'
                  | 'fluent'
                  | 'fortran-fixed-form'
                  | 'fortran-free-form'
                  | 'fsharp'
                  | 'gdresource'
                  | 'gdscript'
                  | 'gdshader'
                  | 'genie'
                  | 'gherkin'
                  | 'git-commit'
                  | 'git-rebase'
                  | 'gleam'
                  | 'glimmer-js'
                  | 'glimmer-ts'
                  | 'glsl'
                  | 'gnuplot'
                  | 'go'
                  | 'graphql'
                  | 'groovy'
                  | 'hack'
                  | 'haml'
                  | 'handlebars'
                  | 'haskell'
                  | 'haxe'
                  | 'hcl'
                  | 'hjson'
                  | 'hlsl'
                  | 'html'
                  | 'html-derivative'
                  | 'http'
                  | 'hurl'
                  | 'hxml'
                  | 'hy'
                  | 'imba'
                  | 'ini'
                  | 'java'
                  | 'javascript'
                  | 'jinja'
                  | 'jison'
                  | 'json'
                  | 'json5'
                  | 'jsonc'
                  | 'jsonl'
                  | 'jsonnet'
                  | 'jssm'
                  | 'jsx'
                  | 'julia'
                  | 'kdl'
                  | 'kotlin'
                  | 'kusto'
                  | 'latex'
                  | 'lean'
                  | 'less'
                  | 'liquid'
                  | 'llvm'
                  | 'log'
                  | 'logo'
                  | 'lua'
                  | 'luau'
                  | 'make'
                  | 'markdown'
                  | 'marko'
                  | 'matlab'
                  | 'mdc'
                  | 'mdx'
                  | 'mermaid'
                  | 'mipsasm'
                  | 'mojo'
                  | 'move'
                  | 'narrat'
                  | 'nextflow'
                  | 'nginx'
                  | 'nim'
                  | 'nix'
                  | 'nushell'
                  | 'objective-c'
                  | 'objective-cpp'
                  | 'ocaml'
                  | 'pascal'
                  | 'perl'
                  | 'php'
                  | 'pkl'
                  | 'plsql'
                  | 'po'
                  | 'polar'
                  | 'postcss'
                  | 'powerquery'
                  | 'powershell'
                  | 'prisma'
                  | 'prolog'
                  | 'proto'
                  | 'pug'
                  | 'puppet'
                  | 'purescript'
                  | 'python'
                  | 'qml'
                  | 'qmldir'
                  | 'qss'
                  | 'r'
                  | 'racket'
                  | 'raku'
                  | 'razor'
                  | 'reg'
                  | 'regexp'
                  | 'rel'
                  | 'riscv'
                  | 'rosmsg'
                  | 'rst'
                  | 'ruby'
                  | 'rust'
                  | 'sas'
                  | 'sass'
                  | 'scala'
                  | 'scheme'
                  | 'scss'
                  | 'sdbl'
                  | 'shaderlab'
                  | 'shellscript'
                  | 'shellsession'
                  | 'smalltalk'
                  | 'solidity'
                  | 'soy'
                  | 'sparql'
                  | 'splunk'
                  | 'sql'
                  | 'ssh-config'
                  | 'stata'
                  | 'stylus'
                  | 'svelte'
                  | 'swift'
                  | 'system-verilog'
                  | 'systemd'
                  | 'talonscript'
                  | 'tasl'
                  | 'tcl'
                  | 'templ'
                  | 'terraform'
                  | 'tex'
                  | 'toml'
                  | 'ts-tags'
                  | 'tsv'
                  | 'tsx'
                  | 'turtle'
                  | 'twig'
                  | 'typescript'
                  | 'typespec'
                  | 'typst'
                  | 'v'
                  | 'vala'
                  | 'vb'
                  | 'verilog'
                  | 'vhdl'
                  | 'viml'
                  | 'vue'
                  | 'vue-html'
                  | 'vue-vine'
                  | 'vyper'
                  | 'wasm'
                  | 'wenyan'
                  | 'wgsl'
                  | 'wikitext'
                  | 'wit'
                  | 'wolfram'
                  | 'xml'
                  | 'xsl'
                  | 'yaml'
                  | 'zenscript'
                  | 'zig'
                  | 'adoc'
                  | 'batch'
                  | 'be'
                  | '1c'
                  | 'cdc'
                  | 'clj'
                  | 'ql'
                  | 'coffeescript'
                  | 'lisp'
                  | 'c++'
                  | 'c#'
                  | 'cs'
                  | 'cql'
                  | 'dockerfile'
                  | 'elisp'
                  | 'erl'
                  | 'ftl'
                  | 'f'
                  | 'for'
                  | 'f77'
                  | 'f90'
                  | 'f95'
                  | 'f03'
                  | 'f08'
                  | 'f18'
                  | 'f#'
                  | 'fs'
                  | 'gjs'
                  | 'gts'
                  | 'gql'
                  | 'hbs'
                  | 'hs'
                  | 'properties'
                  | 'js'
                  | 'cjs'
                  | 'mjs'
                  | 'fsl'
                  | 'jl'
                  | 'kt'
                  | 'kts'
                  | 'kql'
                  | 'lean4'
                  | 'makefile'
                  | 'md'
                  | 'mmd'
                  | 'mips'
                  | 'nar'
                  | 'nf'
                  | 'nu'
                  | 'objc'
                  | 'pot'
                  | 'potx'
                  | 'ps'
                  | 'ps1'
                  | 'protobuf'
                  | 'jade'
                  | 'py'
                  | 'perl6'
                  | 'regex'
                  | 'rb'
                  | 'rs'
                  | '1c-query'
                  | 'shader'
                  | 'bash'
                  | 'sh'
                  | 'shell'
                  | 'zsh'
                  | 'console'
                  | 'closure-templates'
                  | 'spl'
                  | 'styl'
                  | 'talon'
                  | 'tf'
                  | 'tfvars'
                  | 'lit'
                  | 'ts'
                  | 'cts'
                  | 'mts'
                  | 'tsp'
                  | 'typ'
                  | 'cmd'
                  | 'vim'
                  | 'vimscript'
                  | 'vy'
                  | '文言'
                  | 'mediawiki'
                  | 'wiki'
                  | 'wl'
                  | 'yml'
                )
              | null;
            commandMap: {
              [k: string]: string;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'ScriptCopyBtn';
          }
        | {
            quote?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'Quote';
          }
        | {
            tweetId: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'TweetCard';
          }
      )[]
    | null;
  authors?: (number | User)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'blogPosts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogPosts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  content?:
    | T
    | {
        Paragraph?:
          | T
          | {
              paragraph?: T;
              id?: T;
              blockName?: T;
            };
        Code?:
          | T
          | {
              code?: T;
              id?: T;
              blockName?: T;
            };
        ScriptCopyBtn?:
          | T
          | {
              showMultiplePackageOptions?: T;
              codeLanguage?: T;
              commandMap?: T;
              id?: T;
              blockName?: T;
            };
        Quote?:
          | T
          | {
              quote?: T;
              id?: T;
              blockName?: T;
            };
        TweetCard?:
          | T
          | {
              tweetId?: T;
              id?: T;
              blockName?: T;
            };
      };
  authors?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}